### PR TITLE
Fixed image size and alignment issues

### PR DESCRIPTION
**Pull request by pavankumarj**
# Related Issue

- There is a disparity between web and mobile in the following areas
   - size: stretch
   - horizontalAlignment
   - resizeMode

# Description
- Fixed horizontal alignment issue for images with no properties
- Fixed horizontal alignment issue for images with size defined
- Fixed size value "stretch" value of image to match web experience, where the image will be stretched to match the width of the container and the aspect ratio will be set to 1 to maintain height proportionality
- Added resizeMode to stretch to match web experience

# Sample Card

Sample payload used for verification: [image_payload.txt](https://github.com/BigThinkcode/AdaptiveCards/files/7183754/image_payload.txt)

# How Verified

How you verified the fix, including one or all of the following:
1. Unit tests have not been added since these are regression changes and no new functionality is included
2. Different image scenarios with and without any parent containers have been tested, the testing was mainly focused on bringing parity between web and mobile.

### CODE REVIEW

**Comment by IbrahimSulai** [comment]
@pavankumarj - Please change the base branch to [release-2.2.12](https://github.com/BigThinkcode/AdaptiveCards/tree/reactnative/release-2.2.12)

**Comment by pavankumarj** [comment]
@IbrahimSulai @Vasanth-S Updated the base branch

**Review by IbrahimSulai — APPROVED** [review]
LGTM

**Comment by IbrahimSulai** [comment]
@pavankumarj - I have tested the changes with our payloads and scenarios. It looks good. Please also test with the payloads and scenarios used on your side.

**Comment by vivekvijayakrishnan** [comment]
@pavankumarj There were some conflicts in the release-2.2.12 branch and I have resolved them. Could you please update your branch with the latest changes and resolve the conflicts in your branch?

Changes look good to me. 👍

**Comment by IbrahimSulai** [comment]
@vivekvijayakrishnan - This PR showing 37 file changes. Please have a look at the same.

**Pull request closed without merging**
