### PR TITLE
Fixed Keyboard hiding and scroll issue

### PR DESCRIPTION
**Pull request by nikitawani07**
### Description

Adds KeyboardAwareScrollView library to fix keyboard hiding and scroll issues.

Related links:
https://github.com/facebook/react-native/issues/29614 
https://github.com/facebook/react-native/issues/27526 
https://stackoverflow.com/questions/56421280/how-do-fix-the-white-keyboard-space-that-shows-whenever-i-use-keyboardawareview 
https://github.com/facebook/react-native/issues/10765 

### How Verified

https://user-images.githubusercontent.com/25148603/153042052-053c267d-03a4-4274-a098-1dc277f58ed6.mov

https://user-images.githubusercontent.com/25148603/153042103-0d62847e-c04e-47be-8020-7a966a2496ec.mov

https://user-images.githubusercontent.com/25148603/153042291-866daeea-fb53-472a-ad13-57242c79b7ae.mp4

https://user-images.githubusercontent.com/25148603/153042454-6b5632e6-97d1-46d5-90c5-6868c0469a88.mp4

### CODE REVIEW

**Review by vivekkozhisseri — DISMISSED** [review]
LGTM

**Review by Zaidos9 — CHANGES_REQUESTED** [review]
We will wait for answers to following questions before merging the PR :

- will addition of new library require host app to add the library as dependency?
- does it have any impact on accessibility?

**Review by pavankumarj — APPROVED** [review]

**Review by Zaidos9 — APPROVED** [review]
LGTM

**Review by vivekkozhisseri — APPROVED** [review]
LGTM

**Pull request merged**
