### PR TITLE
Generate synthetic dataset

### PR DESCRIPTION
**Pull request by amitramachandran**
## To create synthetic dataset for training purposes

Created a datagen module that has the utility functions to generate the synthetic image dataset from the parts of images or card elements stored in the card_elements directory under the folder _synthetic_ under _data_ 

The card elements are stored in such a way that it can be expanded to add more to the existing list (actionset , choiceset, textbox, images)

The wrapper command around the datagen module is used to create the images in bulk or single either zipped or unzipped with annotations included. 

### Usage

`python -m commands.generate_synthetic_dataset`

To generate zip files:
`python -m commands.generate_synthetic_dataset -z True`

To create images with coloured backgrounds 
`python -m commands.generate_synthetic_dataset -c "ROSE"`

### CODE REVIEW

**Comment by amitramachandran** [comment]
@haridas @Keerthana786 Kindly review. the reviewer side bar doesnt seem to work after opening the PR.

**Comment by haridas** [comment]
The branching convention you can follow, instead of sending the PR to main, send it to feature base branch.

**Review by haridas — COMMENTED** [review]
The code looks good to me. We can proceed once the target branch changes.

**Review by haridas — APPROVED** [review]
LGTM

**Review by Keerthana786 — APPROVED** [review]
LGTM

**Pull request merged**
