### PR TITLE
Fixing Action orientation in vertical state

### PR DESCRIPTION
**Pull request by pavankumarj**
# Related Issue
Issues
1. Vertical alignment for actions in Host Config is not working as expected - breaking structure padding and margins when there are multiple actions defined
btc_actions_before

2. Button spacing not as expected - can be structured in a better way
btc_actions_spacing

# Web behavior
btc_actions_web1

btc_actions_web2

# Fixes

1. btc_actions_after

2. btc_actions_spacing_after

# Sample Card
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Your registration is almost complete",
            "size": "Medium",
            "weight": "Bolder"
        },
        {
            "type": "TextBlock",
            "text": "What type of food do you prefer?",
            "wrap": true
        },
        {
            "type": "ImageSet",
            "images": [
                {
                    "type": "Image",
                    "url": "https://contososcubademo.azurewebsites.net/assets/steak.jpg",
                    "size": "Medium"
                },
                {
                    "type": "Image",
                    "url": "https://contososcubademo.azurewebsites.net/assets/chicken.jpg",
                    "size": "Medium"
                },
                {
                    "type": "Image",
                    "url": "https://contososcubademo.azurewebsites.net/assets/tofu.jpg",
                    "size": "Medium"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.ShowCard",
            "title": "Steak",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "How would you like your steak prepared?",
                        "size": "Medium",
                        "wrap": true
                    },
                    {
                        "type": "Input.ChoiceSet",
                        "id": "SteakTemp",
                        "style": "expanded",
                        "choices": [
                            {
                                "title": "Rare",
                                "value": "rare"
                            },
                            {
                                "title": "Medium-Rare",
                                "value": "medium-rare"
                            },
                            {
                                "title": "Well-done",
                                "value": "well-done"
                            }
                        ]
                    },
                    {
                        "type": "Input.Text",
                        "id": "SteakOther",
                        "isMultiline": true,
                        "placeholder": "Any other preparation requests?"
                    }
                ],
                "actions": [
                    {
                        "type": "Action.Submit",
                        "title": "OK",
                        "data": {
                            "FoodChoice": "Steak"
                        }
                    }
                ]
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Chicken",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Do you have any allergies?",
                        "size": "Medium",
                        "wrap": true
                    },
                    {
                        "type": "Input.ChoiceSet",
                        "id": "ChickenAllergy",
                        "style": "expanded",
                        "isMultiSelect": true,
                        "choices": [
                            {
                                "title": "I'm allergic to peanuts",
                                "value": "peanut"
                            }
                        ]
                    },
                    {
                        "type": "Input.Text",
                        "id": "ChickenOther",
                        "isMultiline": true,
                        "placeholder": "Any other preparation requests?"
                    }
                ],
                "actions": [
                    {
                        "type": "Action.Submit",
                        "title": "OK",
                        "data": {
                            "FoodChoice": "Chicken"
                        }
                    }
                ]
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Chicken XYZ",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Do you have any allergies?",
                        "size": "Medium",
                        "wrap": true
                    },
                    {
                        "type": "Input.ChoiceSet",
                        "id": "Chicken XYZ",
                        "style": "expanded",
                        "isMultiSelect": true,
                        "choices": [
                            {
                                "title": "I'm allergic to peanuts",
                                "value": "peanut"
                            }
                        ]
                    },
                    {
                        "type": "Input.Text",
                        "id": "ChickenOther Xy",
                        "isMultiline": true,
                        "placeholder": "Any other preparation requests?"
                    }
                ],
                "actions": [
                    {
                        "type": "Action.Submit",
                        "title": "OK",
                        "data": {
                            "FoodChoice": "Chicken"
                        }
                    }
                ]
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Chicken 123",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Do you have any allergies?",
                        "size": "Medium",
                        "wrap": true
                    },
                    {
                        "type": "Input.ChoiceSet",
                        "id": "Chicken 123",
                        "style": "expanded",
                        "isMultiSelect": true,
                        "choices": [
                            {
                                "title": "I'm allergic to peanuts",
                                "value": "peanut"
                            }
                        ]
                    },
                    {
                        "type": "Input.Text",
                        "id": "Chicken 1234",
                        "isMultiline": true,
                        "placeholder": "Any other preparation requests?"
                    }
                ],
                "actions": [
                    {
                        "type": "Action.Submit",
                        "title": "OK",
                        "data": {
                            "FoodChoice": "Chicken"
                        }
                    }
                ]
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Tofu",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Would you like it prepared vegan?",
                        "size": "Medium",
                        "wrap": true
                    },
                    {
                        "type": "Input.Toggle",
                        "id": "Vegetarian",
                        "title": "Please prepare it vegan",
                        "valueOn": "vegan",
                        "valueOff": "notVegan"
                    },
                    {
                        "type": "Input.Text",
                        "id": "VegOther",
                        "isMultiline": true,
                        "placeholder": "Any other preparation requests?"
                    }
                ],
                "actions": [
                    {
                        "type": "Action.Submit",
                        "title": "OK",
                        "data": {
                            "FoodChoice": "Vegetarian"
                        }
                    }
                ]
            }
        }
    ]
}`

# How Verified

How you verified the fix, including one or all of the following:
1. Manually tested on Android and iOS devices

### CODE REVIEW

**Comment by IbrahimSulai** [comment]
@pavankumarj - Please update the PR details in the description

**Comment by IbrahimSulai** [comment]
@pavankumarj - This PR is completed or WIP?

**Comment by pavankumarj** [comment]
Hey Ibrahim, this is WIP

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IbrahimSulai** [comment]
> Hey Ibrahim, this is WIP Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: IbrahimSulai ***@***.***> Sent: Wednesday, November 17, 2021 10:41:59 PM To: BigThinkcode/AdaptiveCards ***@***.***> Cc: Pavan Kumar ***@***.***>; Mention ***@***.***> Subject: Re: [BigThinkcode/AdaptiveCards] Fixing Action orientation in vertical state (PR #44) @pavankumarj<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpavankumarj&data=04%7C01%7Cpavanj%40microsoft.com%7C5e1964a7c1554592df0408d9a9ed5df5%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637727659264098141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=khsfn7cPfMeMXd1E70uKwe81vme5vGwjFTmskI8SK7w%3D&reserved=0> - This PR is completed or WIP? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBigThinkcode%2FAdaptiveCards%2Fpull%2F44%23issuecomment-971784371&data=04%7C01%7Cpavanj%40microsoft.com%7C5e1964a7c1554592df0408d9a9ed5df5%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637727659264108098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fnan3MBsMRWJJmmDod%2BSm5n8RyZ38RY72kYkbFwl0u4%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASBXX5J2DQN4MWSPTM5VTKLUMPO57ANCNFSM5ID66JFA&data=04%7C01%7Cpavanj%40microsoft.com%7C5e1964a7c1554592df0408d9a9ed5df5%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637727659264108098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QTcHCaPioSItVXFhcETkF2XV5DKJH0HuQiR4kXJBao4%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpavanj%40microsoft.com%7C5e1964a7c1554592df0408d9a9ed5df5%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637727659264118053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6QZolI4c21NJ3uBAV0mC0FVQ%2B9aOEQ9wOUyDruV65Wk%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpavanj%40microsoft.com%7C5e1964a7c1554592df0408d9a9ed5df5%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637727659264118053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gI7SstMJWfDZbci71PbibnLhofFTvN8ePlgqvrZunec%3D&reserved=0>.

Thanks.
I have added the WIP in the title for reference.

**Review by IbrahimSulai — APPROVED** [review]
LGTM

**Pull request merged**
