### PR TITLE
Handled the default style container with the parent having a background image

### PR DESCRIPTION
**Pull request by IbrahimSulai**
Handled the default style container with the parent having a background image

### CODE REVIEW

**Comment by pavankumarj** [comment]
@Vasanth-S @pragadeeshk @IbrahimSulai 

Here are the scenarios we have tested against

[Working scenarios.zip](https://github.com/BigThinkcode/AdaptiveCards/files/8022587/Working.scenarios.zip)

[Scenarios not working.zip](https://github.com/BigThinkcode/AdaptiveCards/files/8022594/Scenarios.not.working.zip)

**Comment by IbrahimSulai** [comment]
@pavankumarj @Zaidos9 - I have handled the padding for the scenario with the container having a background image. Please validate the same.

cc: @pragadeeshk @vivekvijayakrishnan @Vasanth-S

**Comment by IbrahimSulai** [comment]
> @pavankumarj @Zaidos9 - I have handled the padding for the scenario with the container having a background image. Please validate the same.
> 
> cc: @pragadeeshk @vivekvijayakrishnan @Vasanth-S

@pavankumarj @Zaidos9 - Gentle Reminder. Please review the same.
cc: @vivekvijayakrishnan @pragadeeshk @Vasanth-S

**Comment by IbrahimSulai** [comment]
@pavankumarj - Could you please confirm once the testing is completed?

cc @Zaidos9 @pragadeeshk @vivekvijayakrishnan @Vasanth-S

**Comment by IbrahimSulai** [comment]
Due to multiple conflicts, I am Closing this PR. 
I will create a new PR with these changes and a few more updates.

**Comment by pavankumarj** [comment]
@Ibrahim ***@***.***> I am done with the validation of half of the test cases. Working on rest of them today. Will let you know once completed. I couldn't work on it last week because of a hackathon. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
