### PR TITLE
Fixed selected value issue for Date/Time component

### PR DESCRIPTION
**Pull request by nikitawani07**
### Description

This PR:
- [iOS] Fixes selected value issue for date/time component based on given default value and range given in the payload. For range date/time case:
i. If no default value is given, it selects maximum value from payload or current date/time. 
ii. If given default value is not within the range, it selects minimum or maximum value from payload depending on the given default value.

- [Both] Default error message ("Required") will now be displayed only in case of empty required field. As earlier, it displayed wrong message in case of other error scenarios also when no error message was present in payload.

### How Verified

- **Input - Error Message**

Platform | Before(Out of range) | After(Out of range) | Before(Empty required field) | After(Empty required field)
| - | - | - | - | -
iOS | [ErrorBefore1]  | [ErrorAfter1] | [ErrorBefore2] | [ErrorAfter2]
Android |  [ErrorBefore3] |  [ErrorAfter3] |  [ErrorBefore4] |  [ErrorAfter4]

- **Date/Time** 

https://user-images.githubusercontent.com/25148603/149968000-36c9b7d3-61ec-4249-a78f-6435cdae013d.mov

https://user-images.githubusercontent.com/25148603/149968259-3faad0f3-0e1b-4ed0-97ec-4532edec3095.mov

For range as  {"min": "2017-09-20", "max": "2017-09-22"}

https://user-images.githubusercontent.com/25148603/150326254-6bbf4249-e196-46e9-a1e9-003ca7fc3ec2.mov

https://user-images.githubusercontent.com/25148603/150326347-06a1fd08-ce81-4c09-bbc0-68e45abfc727.mov

### CODE REVIEW

**Comment by nikitawani07** [comment]
@vivekvijayakrishnan @pragadeeshk  @IbrahimSulai @Vasanth-S @Zaidos9
Added empty value check for default required error message as discussed. Please review.

**Review by vivekkozhisseri — APPROVED** [review]
LGTM

**Review by Vasanth-S — APPROVED** [review]
LGTM

**Review by Zaidos9 — APPROVED** [review]
LGTM

**Pull request merged**
